# Generated by Django 6.0.3 on 2026-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
